// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bbs.proto

#include "bbs.pb.h"
#include "bbs.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace bbs {

static const char* BbsService_method_names[] = {
  "/bbs.BbsService/GetForums",
  "/bbs.BbsService/GetForumDetail",
  "/bbs.BbsService/FollowForum",
  "/bbs.BbsService/UnfollowForum",
  "/bbs.BbsService/GetFollowedForums",
  "/bbs.BbsService/ListPosts",
  "/bbs.BbsService/GetPostDetail",
  "/bbs.BbsService/CreatePost",
  "/bbs.BbsService/UpdatePost",
  "/bbs.BbsService/DeletePost",
  "/bbs.BbsService/LikePost",
  "/bbs.BbsService/UnlikePost",
  "/bbs.BbsService/CollectPost",
  "/bbs.BbsService/UncollectPost",
  "/bbs.BbsService/SetTopPost",
  "/bbs.BbsService/SetEssencePost",
  "/bbs.BbsService/ListReplies",
  "/bbs.BbsService/CreateReply",
  "/bbs.BbsService/DeleteReply",
  "/bbs.BbsService/LikeReply",
  "/bbs.BbsService/UnlikeReply",
  "/bbs.BbsService/Search",
  "/bbs.BbsService/MyPosts",
  "/bbs.BbsService/MyReplies",
  "/bbs.BbsService/MyCollections",
  "/bbs.BbsService/MyFollowers",
  "/bbs.BbsService/MyFollowing",
};

std::unique_ptr< BbsService::Stub> BbsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BbsService::Stub> stub(new BbsService::Stub(channel, options));
  return stub;
}

BbsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetForums_(BbsService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetForumDetail_(BbsService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FollowForum_(BbsService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UnfollowForum_(BbsService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetFollowedForums_(BbsService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListPosts_(BbsService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPostDetail_(BbsService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreatePost_(BbsService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdatePost_(BbsService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeletePost_(BbsService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LikePost_(BbsService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UnlikePost_(BbsService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CollectPost_(BbsService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UncollectPost_(BbsService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetTopPost_(BbsService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetEssencePost_(BbsService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListReplies_(BbsService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateReply_(BbsService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteReply_(BbsService_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LikeReply_(BbsService_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UnlikeReply_(BbsService_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Search_(BbsService_method_names[21], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MyPosts_(BbsService_method_names[22], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MyReplies_(BbsService_method_names[23], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MyCollections_(BbsService_method_names[24], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MyFollowers_(BbsService_method_names[25], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MyFollowing_(BbsService_method_names[26], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BbsService::Stub::GetForums(::grpc::ClientContext* context, const ::bbs::ForumsReq& request, ::bbs::ForumsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::ForumsReq, ::bbs::ForumsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetForums_, context, request, response);
}

void BbsService::Stub::async::GetForums(::grpc::ClientContext* context, const ::bbs::ForumsReq* request, ::bbs::ForumsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::ForumsReq, ::bbs::ForumsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetForums_, context, request, response, std::move(f));
}

void BbsService::Stub::async::GetForums(::grpc::ClientContext* context, const ::bbs::ForumsReq* request, ::bbs::ForumsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetForums_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::ForumsResp>* BbsService::Stub::PrepareAsyncGetForumsRaw(::grpc::ClientContext* context, const ::bbs::ForumsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::ForumsResp, ::bbs::ForumsReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetForums_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::ForumsResp>* BbsService::Stub::AsyncGetForumsRaw(::grpc::ClientContext* context, const ::bbs::ForumsReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetForumsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::GetForumDetail(::grpc::ClientContext* context, const ::bbs::ForumDetailReq& request, ::bbs::ForumDetailResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::ForumDetailReq, ::bbs::ForumDetailResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetForumDetail_, context, request, response);
}

void BbsService::Stub::async::GetForumDetail(::grpc::ClientContext* context, const ::bbs::ForumDetailReq* request, ::bbs::ForumDetailResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::ForumDetailReq, ::bbs::ForumDetailResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetForumDetail_, context, request, response, std::move(f));
}

void BbsService::Stub::async::GetForumDetail(::grpc::ClientContext* context, const ::bbs::ForumDetailReq* request, ::bbs::ForumDetailResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetForumDetail_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::ForumDetailResp>* BbsService::Stub::PrepareAsyncGetForumDetailRaw(::grpc::ClientContext* context, const ::bbs::ForumDetailReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::ForumDetailResp, ::bbs::ForumDetailReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetForumDetail_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::ForumDetailResp>* BbsService::Stub::AsyncGetForumDetailRaw(::grpc::ClientContext* context, const ::bbs::ForumDetailReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetForumDetailRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::FollowForum(::grpc::ClientContext* context, const ::bbs::FollowForumReq& request, ::bbs::FollowForumResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::FollowForumReq, ::bbs::FollowForumResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FollowForum_, context, request, response);
}

void BbsService::Stub::async::FollowForum(::grpc::ClientContext* context, const ::bbs::FollowForumReq* request, ::bbs::FollowForumResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::FollowForumReq, ::bbs::FollowForumResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FollowForum_, context, request, response, std::move(f));
}

void BbsService::Stub::async::FollowForum(::grpc::ClientContext* context, const ::bbs::FollowForumReq* request, ::bbs::FollowForumResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FollowForum_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::FollowForumResp>* BbsService::Stub::PrepareAsyncFollowForumRaw(::grpc::ClientContext* context, const ::bbs::FollowForumReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::FollowForumResp, ::bbs::FollowForumReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FollowForum_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::FollowForumResp>* BbsService::Stub::AsyncFollowForumRaw(::grpc::ClientContext* context, const ::bbs::FollowForumReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFollowForumRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::UnfollowForum(::grpc::ClientContext* context, const ::bbs::FollowForumReq& request, ::bbs::FollowForumResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::FollowForumReq, ::bbs::FollowForumResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnfollowForum_, context, request, response);
}

void BbsService::Stub::async::UnfollowForum(::grpc::ClientContext* context, const ::bbs::FollowForumReq* request, ::bbs::FollowForumResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::FollowForumReq, ::bbs::FollowForumResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnfollowForum_, context, request, response, std::move(f));
}

void BbsService::Stub::async::UnfollowForum(::grpc::ClientContext* context, const ::bbs::FollowForumReq* request, ::bbs::FollowForumResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnfollowForum_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::FollowForumResp>* BbsService::Stub::PrepareAsyncUnfollowForumRaw(::grpc::ClientContext* context, const ::bbs::FollowForumReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::FollowForumResp, ::bbs::FollowForumReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnfollowForum_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::FollowForumResp>* BbsService::Stub::AsyncUnfollowForumRaw(::grpc::ClientContext* context, const ::bbs::FollowForumReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnfollowForumRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::GetFollowedForums(::grpc::ClientContext* context, const ::bbs::FollowedForumsReq& request, ::bbs::FollowedForumsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::FollowedForumsReq, ::bbs::FollowedForumsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFollowedForums_, context, request, response);
}

void BbsService::Stub::async::GetFollowedForums(::grpc::ClientContext* context, const ::bbs::FollowedForumsReq* request, ::bbs::FollowedForumsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::FollowedForumsReq, ::bbs::FollowedForumsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFollowedForums_, context, request, response, std::move(f));
}

void BbsService::Stub::async::GetFollowedForums(::grpc::ClientContext* context, const ::bbs::FollowedForumsReq* request, ::bbs::FollowedForumsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFollowedForums_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::FollowedForumsResp>* BbsService::Stub::PrepareAsyncGetFollowedForumsRaw(::grpc::ClientContext* context, const ::bbs::FollowedForumsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::FollowedForumsResp, ::bbs::FollowedForumsReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFollowedForums_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::FollowedForumsResp>* BbsService::Stub::AsyncGetFollowedForumsRaw(::grpc::ClientContext* context, const ::bbs::FollowedForumsReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFollowedForumsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::ListPosts(::grpc::ClientContext* context, const ::bbs::PostsReq& request, ::bbs::PostsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::PostsReq, ::bbs::PostsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListPosts_, context, request, response);
}

void BbsService::Stub::async::ListPosts(::grpc::ClientContext* context, const ::bbs::PostsReq* request, ::bbs::PostsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::PostsReq, ::bbs::PostsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPosts_, context, request, response, std::move(f));
}

void BbsService::Stub::async::ListPosts(::grpc::ClientContext* context, const ::bbs::PostsReq* request, ::bbs::PostsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPosts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::PostsResp>* BbsService::Stub::PrepareAsyncListPostsRaw(::grpc::ClientContext* context, const ::bbs::PostsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::PostsResp, ::bbs::PostsReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListPosts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::PostsResp>* BbsService::Stub::AsyncListPostsRaw(::grpc::ClientContext* context, const ::bbs::PostsReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListPostsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::GetPostDetail(::grpc::ClientContext* context, const ::bbs::PostDetailReq& request, ::bbs::PostDetailResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::PostDetailReq, ::bbs::PostDetailResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPostDetail_, context, request, response);
}

void BbsService::Stub::async::GetPostDetail(::grpc::ClientContext* context, const ::bbs::PostDetailReq* request, ::bbs::PostDetailResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::PostDetailReq, ::bbs::PostDetailResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPostDetail_, context, request, response, std::move(f));
}

void BbsService::Stub::async::GetPostDetail(::grpc::ClientContext* context, const ::bbs::PostDetailReq* request, ::bbs::PostDetailResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPostDetail_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::PostDetailResp>* BbsService::Stub::PrepareAsyncGetPostDetailRaw(::grpc::ClientContext* context, const ::bbs::PostDetailReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::PostDetailResp, ::bbs::PostDetailReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPostDetail_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::PostDetailResp>* BbsService::Stub::AsyncGetPostDetailRaw(::grpc::ClientContext* context, const ::bbs::PostDetailReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPostDetailRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::CreatePost(::grpc::ClientContext* context, const ::bbs::CreatePostReq& request, ::bbs::CreatePostResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::CreatePostReq, ::bbs::CreatePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreatePost_, context, request, response);
}

void BbsService::Stub::async::CreatePost(::grpc::ClientContext* context, const ::bbs::CreatePostReq* request, ::bbs::CreatePostResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::CreatePostReq, ::bbs::CreatePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreatePost_, context, request, response, std::move(f));
}

void BbsService::Stub::async::CreatePost(::grpc::ClientContext* context, const ::bbs::CreatePostReq* request, ::bbs::CreatePostResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreatePost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::CreatePostResp>* BbsService::Stub::PrepareAsyncCreatePostRaw(::grpc::ClientContext* context, const ::bbs::CreatePostReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::CreatePostResp, ::bbs::CreatePostReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreatePost_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::CreatePostResp>* BbsService::Stub::AsyncCreatePostRaw(::grpc::ClientContext* context, const ::bbs::CreatePostReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreatePostRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::UpdatePost(::grpc::ClientContext* context, const ::bbs::UpdatePostReq& request, ::bbs::UpdatePostResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::UpdatePostReq, ::bbs::UpdatePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdatePost_, context, request, response);
}

void BbsService::Stub::async::UpdatePost(::grpc::ClientContext* context, const ::bbs::UpdatePostReq* request, ::bbs::UpdatePostResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::UpdatePostReq, ::bbs::UpdatePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdatePost_, context, request, response, std::move(f));
}

void BbsService::Stub::async::UpdatePost(::grpc::ClientContext* context, const ::bbs::UpdatePostReq* request, ::bbs::UpdatePostResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdatePost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::UpdatePostResp>* BbsService::Stub::PrepareAsyncUpdatePostRaw(::grpc::ClientContext* context, const ::bbs::UpdatePostReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::UpdatePostResp, ::bbs::UpdatePostReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdatePost_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::UpdatePostResp>* BbsService::Stub::AsyncUpdatePostRaw(::grpc::ClientContext* context, const ::bbs::UpdatePostReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdatePostRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::DeletePost(::grpc::ClientContext* context, const ::bbs::DeletePostReq& request, ::bbs::DeletePostResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::DeletePostReq, ::bbs::DeletePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeletePost_, context, request, response);
}

void BbsService::Stub::async::DeletePost(::grpc::ClientContext* context, const ::bbs::DeletePostReq* request, ::bbs::DeletePostResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::DeletePostReq, ::bbs::DeletePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeletePost_, context, request, response, std::move(f));
}

void BbsService::Stub::async::DeletePost(::grpc::ClientContext* context, const ::bbs::DeletePostReq* request, ::bbs::DeletePostResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeletePost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::DeletePostResp>* BbsService::Stub::PrepareAsyncDeletePostRaw(::grpc::ClientContext* context, const ::bbs::DeletePostReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::DeletePostResp, ::bbs::DeletePostReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeletePost_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::DeletePostResp>* BbsService::Stub::AsyncDeletePostRaw(::grpc::ClientContext* context, const ::bbs::DeletePostReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeletePostRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::LikePost(::grpc::ClientContext* context, const ::bbs::LikePostReq& request, ::bbs::LikePostResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::LikePostReq, ::bbs::LikePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LikePost_, context, request, response);
}

void BbsService::Stub::async::LikePost(::grpc::ClientContext* context, const ::bbs::LikePostReq* request, ::bbs::LikePostResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::LikePostReq, ::bbs::LikePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LikePost_, context, request, response, std::move(f));
}

void BbsService::Stub::async::LikePost(::grpc::ClientContext* context, const ::bbs::LikePostReq* request, ::bbs::LikePostResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LikePost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::LikePostResp>* BbsService::Stub::PrepareAsyncLikePostRaw(::grpc::ClientContext* context, const ::bbs::LikePostReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::LikePostResp, ::bbs::LikePostReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LikePost_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::LikePostResp>* BbsService::Stub::AsyncLikePostRaw(::grpc::ClientContext* context, const ::bbs::LikePostReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLikePostRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::UnlikePost(::grpc::ClientContext* context, const ::bbs::LikePostReq& request, ::bbs::LikePostResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::LikePostReq, ::bbs::LikePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnlikePost_, context, request, response);
}

void BbsService::Stub::async::UnlikePost(::grpc::ClientContext* context, const ::bbs::LikePostReq* request, ::bbs::LikePostResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::LikePostReq, ::bbs::LikePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnlikePost_, context, request, response, std::move(f));
}

void BbsService::Stub::async::UnlikePost(::grpc::ClientContext* context, const ::bbs::LikePostReq* request, ::bbs::LikePostResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnlikePost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::LikePostResp>* BbsService::Stub::PrepareAsyncUnlikePostRaw(::grpc::ClientContext* context, const ::bbs::LikePostReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::LikePostResp, ::bbs::LikePostReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnlikePost_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::LikePostResp>* BbsService::Stub::AsyncUnlikePostRaw(::grpc::ClientContext* context, const ::bbs::LikePostReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnlikePostRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::CollectPost(::grpc::ClientContext* context, const ::bbs::CollectPostReq& request, ::bbs::CollectPostResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::CollectPostReq, ::bbs::CollectPostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CollectPost_, context, request, response);
}

void BbsService::Stub::async::CollectPost(::grpc::ClientContext* context, const ::bbs::CollectPostReq* request, ::bbs::CollectPostResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::CollectPostReq, ::bbs::CollectPostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CollectPost_, context, request, response, std::move(f));
}

void BbsService::Stub::async::CollectPost(::grpc::ClientContext* context, const ::bbs::CollectPostReq* request, ::bbs::CollectPostResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CollectPost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::CollectPostResp>* BbsService::Stub::PrepareAsyncCollectPostRaw(::grpc::ClientContext* context, const ::bbs::CollectPostReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::CollectPostResp, ::bbs::CollectPostReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CollectPost_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::CollectPostResp>* BbsService::Stub::AsyncCollectPostRaw(::grpc::ClientContext* context, const ::bbs::CollectPostReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCollectPostRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::UncollectPost(::grpc::ClientContext* context, const ::bbs::CollectPostReq& request, ::bbs::CollectPostResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::CollectPostReq, ::bbs::CollectPostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UncollectPost_, context, request, response);
}

void BbsService::Stub::async::UncollectPost(::grpc::ClientContext* context, const ::bbs::CollectPostReq* request, ::bbs::CollectPostResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::CollectPostReq, ::bbs::CollectPostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UncollectPost_, context, request, response, std::move(f));
}

void BbsService::Stub::async::UncollectPost(::grpc::ClientContext* context, const ::bbs::CollectPostReq* request, ::bbs::CollectPostResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UncollectPost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::CollectPostResp>* BbsService::Stub::PrepareAsyncUncollectPostRaw(::grpc::ClientContext* context, const ::bbs::CollectPostReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::CollectPostResp, ::bbs::CollectPostReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UncollectPost_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::CollectPostResp>* BbsService::Stub::AsyncUncollectPostRaw(::grpc::ClientContext* context, const ::bbs::CollectPostReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUncollectPostRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::SetTopPost(::grpc::ClientContext* context, const ::bbs::SetTopReq& request, ::bbs::SetTopResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::SetTopReq, ::bbs::SetTopResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetTopPost_, context, request, response);
}

void BbsService::Stub::async::SetTopPost(::grpc::ClientContext* context, const ::bbs::SetTopReq* request, ::bbs::SetTopResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::SetTopReq, ::bbs::SetTopResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTopPost_, context, request, response, std::move(f));
}

void BbsService::Stub::async::SetTopPost(::grpc::ClientContext* context, const ::bbs::SetTopReq* request, ::bbs::SetTopResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTopPost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::SetTopResp>* BbsService::Stub::PrepareAsyncSetTopPostRaw(::grpc::ClientContext* context, const ::bbs::SetTopReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::SetTopResp, ::bbs::SetTopReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetTopPost_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::SetTopResp>* BbsService::Stub::AsyncSetTopPostRaw(::grpc::ClientContext* context, const ::bbs::SetTopReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetTopPostRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::SetEssencePost(::grpc::ClientContext* context, const ::bbs::SetEssenceReq& request, ::bbs::SetEssenceResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::SetEssenceReq, ::bbs::SetEssenceResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetEssencePost_, context, request, response);
}

void BbsService::Stub::async::SetEssencePost(::grpc::ClientContext* context, const ::bbs::SetEssenceReq* request, ::bbs::SetEssenceResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::SetEssenceReq, ::bbs::SetEssenceResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetEssencePost_, context, request, response, std::move(f));
}

void BbsService::Stub::async::SetEssencePost(::grpc::ClientContext* context, const ::bbs::SetEssenceReq* request, ::bbs::SetEssenceResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetEssencePost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::SetEssenceResp>* BbsService::Stub::PrepareAsyncSetEssencePostRaw(::grpc::ClientContext* context, const ::bbs::SetEssenceReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::SetEssenceResp, ::bbs::SetEssenceReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetEssencePost_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::SetEssenceResp>* BbsService::Stub::AsyncSetEssencePostRaw(::grpc::ClientContext* context, const ::bbs::SetEssenceReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetEssencePostRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::ListReplies(::grpc::ClientContext* context, const ::bbs::RepliesReq& request, ::bbs::RepliesResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::RepliesReq, ::bbs::RepliesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListReplies_, context, request, response);
}

void BbsService::Stub::async::ListReplies(::grpc::ClientContext* context, const ::bbs::RepliesReq* request, ::bbs::RepliesResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::RepliesReq, ::bbs::RepliesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListReplies_, context, request, response, std::move(f));
}

void BbsService::Stub::async::ListReplies(::grpc::ClientContext* context, const ::bbs::RepliesReq* request, ::bbs::RepliesResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListReplies_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::RepliesResp>* BbsService::Stub::PrepareAsyncListRepliesRaw(::grpc::ClientContext* context, const ::bbs::RepliesReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::RepliesResp, ::bbs::RepliesReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListReplies_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::RepliesResp>* BbsService::Stub::AsyncListRepliesRaw(::grpc::ClientContext* context, const ::bbs::RepliesReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListRepliesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::CreateReply(::grpc::ClientContext* context, const ::bbs::CreateReplyReq& request, ::bbs::CreateReplyResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::CreateReplyReq, ::bbs::CreateReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateReply_, context, request, response);
}

void BbsService::Stub::async::CreateReply(::grpc::ClientContext* context, const ::bbs::CreateReplyReq* request, ::bbs::CreateReplyResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::CreateReplyReq, ::bbs::CreateReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateReply_, context, request, response, std::move(f));
}

void BbsService::Stub::async::CreateReply(::grpc::ClientContext* context, const ::bbs::CreateReplyReq* request, ::bbs::CreateReplyResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateReply_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::CreateReplyResp>* BbsService::Stub::PrepareAsyncCreateReplyRaw(::grpc::ClientContext* context, const ::bbs::CreateReplyReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::CreateReplyResp, ::bbs::CreateReplyReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateReply_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::CreateReplyResp>* BbsService::Stub::AsyncCreateReplyRaw(::grpc::ClientContext* context, const ::bbs::CreateReplyReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateReplyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::DeleteReply(::grpc::ClientContext* context, const ::bbs::DeleteReplyReq& request, ::bbs::DeleteReplyResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::DeleteReplyReq, ::bbs::DeleteReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteReply_, context, request, response);
}

void BbsService::Stub::async::DeleteReply(::grpc::ClientContext* context, const ::bbs::DeleteReplyReq* request, ::bbs::DeleteReplyResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::DeleteReplyReq, ::bbs::DeleteReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteReply_, context, request, response, std::move(f));
}

void BbsService::Stub::async::DeleteReply(::grpc::ClientContext* context, const ::bbs::DeleteReplyReq* request, ::bbs::DeleteReplyResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteReply_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::DeleteReplyResp>* BbsService::Stub::PrepareAsyncDeleteReplyRaw(::grpc::ClientContext* context, const ::bbs::DeleteReplyReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::DeleteReplyResp, ::bbs::DeleteReplyReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteReply_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::DeleteReplyResp>* BbsService::Stub::AsyncDeleteReplyRaw(::grpc::ClientContext* context, const ::bbs::DeleteReplyReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteReplyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::LikeReply(::grpc::ClientContext* context, const ::bbs::LikeReplyReq& request, ::bbs::LikeReplyResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::LikeReplyReq, ::bbs::LikeReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LikeReply_, context, request, response);
}

void BbsService::Stub::async::LikeReply(::grpc::ClientContext* context, const ::bbs::LikeReplyReq* request, ::bbs::LikeReplyResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::LikeReplyReq, ::bbs::LikeReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LikeReply_, context, request, response, std::move(f));
}

void BbsService::Stub::async::LikeReply(::grpc::ClientContext* context, const ::bbs::LikeReplyReq* request, ::bbs::LikeReplyResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LikeReply_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::LikeReplyResp>* BbsService::Stub::PrepareAsyncLikeReplyRaw(::grpc::ClientContext* context, const ::bbs::LikeReplyReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::LikeReplyResp, ::bbs::LikeReplyReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LikeReply_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::LikeReplyResp>* BbsService::Stub::AsyncLikeReplyRaw(::grpc::ClientContext* context, const ::bbs::LikeReplyReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLikeReplyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::UnlikeReply(::grpc::ClientContext* context, const ::bbs::LikeReplyReq& request, ::bbs::LikeReplyResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::LikeReplyReq, ::bbs::LikeReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UnlikeReply_, context, request, response);
}

void BbsService::Stub::async::UnlikeReply(::grpc::ClientContext* context, const ::bbs::LikeReplyReq* request, ::bbs::LikeReplyResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::LikeReplyReq, ::bbs::LikeReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnlikeReply_, context, request, response, std::move(f));
}

void BbsService::Stub::async::UnlikeReply(::grpc::ClientContext* context, const ::bbs::LikeReplyReq* request, ::bbs::LikeReplyResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UnlikeReply_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::LikeReplyResp>* BbsService::Stub::PrepareAsyncUnlikeReplyRaw(::grpc::ClientContext* context, const ::bbs::LikeReplyReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::LikeReplyResp, ::bbs::LikeReplyReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UnlikeReply_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::LikeReplyResp>* BbsService::Stub::AsyncUnlikeReplyRaw(::grpc::ClientContext* context, const ::bbs::LikeReplyReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUnlikeReplyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::Search(::grpc::ClientContext* context, const ::bbs::SearchReq& request, ::bbs::SearchResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::SearchReq, ::bbs::SearchResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Search_, context, request, response);
}

void BbsService::Stub::async::Search(::grpc::ClientContext* context, const ::bbs::SearchReq* request, ::bbs::SearchResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::SearchReq, ::bbs::SearchResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, std::move(f));
}

void BbsService::Stub::async::Search(::grpc::ClientContext* context, const ::bbs::SearchReq* request, ::bbs::SearchResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Search_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::SearchResp>* BbsService::Stub::PrepareAsyncSearchRaw(::grpc::ClientContext* context, const ::bbs::SearchReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::SearchResp, ::bbs::SearchReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Search_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::SearchResp>* BbsService::Stub::AsyncSearchRaw(::grpc::ClientContext* context, const ::bbs::SearchReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSearchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::MyPosts(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::bbs::MyPostsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::MyListReq, ::bbs::MyPostsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MyPosts_, context, request, response);
}

void BbsService::Stub::async::MyPosts(::grpc::ClientContext* context, const ::bbs::MyListReq* request, ::bbs::MyPostsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::MyListReq, ::bbs::MyPostsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyPosts_, context, request, response, std::move(f));
}

void BbsService::Stub::async::MyPosts(::grpc::ClientContext* context, const ::bbs::MyListReq* request, ::bbs::MyPostsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyPosts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::MyPostsResp>* BbsService::Stub::PrepareAsyncMyPostsRaw(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::MyPostsResp, ::bbs::MyListReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MyPosts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::MyPostsResp>* BbsService::Stub::AsyncMyPostsRaw(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMyPostsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::MyReplies(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::bbs::MyRepliesResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::MyListReq, ::bbs::MyRepliesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MyReplies_, context, request, response);
}

void BbsService::Stub::async::MyReplies(::grpc::ClientContext* context, const ::bbs::MyListReq* request, ::bbs::MyRepliesResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::MyListReq, ::bbs::MyRepliesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyReplies_, context, request, response, std::move(f));
}

void BbsService::Stub::async::MyReplies(::grpc::ClientContext* context, const ::bbs::MyListReq* request, ::bbs::MyRepliesResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyReplies_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::MyRepliesResp>* BbsService::Stub::PrepareAsyncMyRepliesRaw(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::MyRepliesResp, ::bbs::MyListReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MyReplies_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::MyRepliesResp>* BbsService::Stub::AsyncMyRepliesRaw(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMyRepliesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::MyCollections(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::bbs::MyCollectionsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::MyListReq, ::bbs::MyCollectionsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MyCollections_, context, request, response);
}

void BbsService::Stub::async::MyCollections(::grpc::ClientContext* context, const ::bbs::MyListReq* request, ::bbs::MyCollectionsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::MyListReq, ::bbs::MyCollectionsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyCollections_, context, request, response, std::move(f));
}

void BbsService::Stub::async::MyCollections(::grpc::ClientContext* context, const ::bbs::MyListReq* request, ::bbs::MyCollectionsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyCollections_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::MyCollectionsResp>* BbsService::Stub::PrepareAsyncMyCollectionsRaw(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::MyCollectionsResp, ::bbs::MyListReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MyCollections_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::MyCollectionsResp>* BbsService::Stub::AsyncMyCollectionsRaw(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMyCollectionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::MyFollowers(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::bbs::MyUsersResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::MyListReq, ::bbs::MyUsersResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MyFollowers_, context, request, response);
}

void BbsService::Stub::async::MyFollowers(::grpc::ClientContext* context, const ::bbs::MyListReq* request, ::bbs::MyUsersResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::MyListReq, ::bbs::MyUsersResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyFollowers_, context, request, response, std::move(f));
}

void BbsService::Stub::async::MyFollowers(::grpc::ClientContext* context, const ::bbs::MyListReq* request, ::bbs::MyUsersResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyFollowers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::MyUsersResp>* BbsService::Stub::PrepareAsyncMyFollowersRaw(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::MyUsersResp, ::bbs::MyListReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MyFollowers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::MyUsersResp>* BbsService::Stub::AsyncMyFollowersRaw(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMyFollowersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BbsService::Stub::MyFollowing(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::bbs::MyUsersResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bbs::MyListReq, ::bbs::MyUsersResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MyFollowing_, context, request, response);
}

void BbsService::Stub::async::MyFollowing(::grpc::ClientContext* context, const ::bbs::MyListReq* request, ::bbs::MyUsersResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bbs::MyListReq, ::bbs::MyUsersResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyFollowing_, context, request, response, std::move(f));
}

void BbsService::Stub::async::MyFollowing(::grpc::ClientContext* context, const ::bbs::MyListReq* request, ::bbs::MyUsersResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyFollowing_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bbs::MyUsersResp>* BbsService::Stub::PrepareAsyncMyFollowingRaw(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bbs::MyUsersResp, ::bbs::MyListReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MyFollowing_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bbs::MyUsersResp>* BbsService::Stub::AsyncMyFollowingRaw(::grpc::ClientContext* context, const ::bbs::MyListReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMyFollowingRaw(context, request, cq);
  result->StartCall();
  return result;
}

BbsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::ForumsReq, ::bbs::ForumsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::ForumsReq* req,
             ::bbs::ForumsResp* resp) {
               return service->GetForums(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::ForumDetailReq, ::bbs::ForumDetailResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::ForumDetailReq* req,
             ::bbs::ForumDetailResp* resp) {
               return service->GetForumDetail(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::FollowForumReq, ::bbs::FollowForumResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::FollowForumReq* req,
             ::bbs::FollowForumResp* resp) {
               return service->FollowForum(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::FollowForumReq, ::bbs::FollowForumResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::FollowForumReq* req,
             ::bbs::FollowForumResp* resp) {
               return service->UnfollowForum(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::FollowedForumsReq, ::bbs::FollowedForumsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::FollowedForumsReq* req,
             ::bbs::FollowedForumsResp* resp) {
               return service->GetFollowedForums(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::PostsReq, ::bbs::PostsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::PostsReq* req,
             ::bbs::PostsResp* resp) {
               return service->ListPosts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::PostDetailReq, ::bbs::PostDetailResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::PostDetailReq* req,
             ::bbs::PostDetailResp* resp) {
               return service->GetPostDetail(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::CreatePostReq, ::bbs::CreatePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::CreatePostReq* req,
             ::bbs::CreatePostResp* resp) {
               return service->CreatePost(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::UpdatePostReq, ::bbs::UpdatePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::UpdatePostReq* req,
             ::bbs::UpdatePostResp* resp) {
               return service->UpdatePost(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::DeletePostReq, ::bbs::DeletePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::DeletePostReq* req,
             ::bbs::DeletePostResp* resp) {
               return service->DeletePost(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::LikePostReq, ::bbs::LikePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::LikePostReq* req,
             ::bbs::LikePostResp* resp) {
               return service->LikePost(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::LikePostReq, ::bbs::LikePostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::LikePostReq* req,
             ::bbs::LikePostResp* resp) {
               return service->UnlikePost(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::CollectPostReq, ::bbs::CollectPostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::CollectPostReq* req,
             ::bbs::CollectPostResp* resp) {
               return service->CollectPost(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::CollectPostReq, ::bbs::CollectPostResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::CollectPostReq* req,
             ::bbs::CollectPostResp* resp) {
               return service->UncollectPost(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::SetTopReq, ::bbs::SetTopResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::SetTopReq* req,
             ::bbs::SetTopResp* resp) {
               return service->SetTopPost(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::SetEssenceReq, ::bbs::SetEssenceResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::SetEssenceReq* req,
             ::bbs::SetEssenceResp* resp) {
               return service->SetEssencePost(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::RepliesReq, ::bbs::RepliesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::RepliesReq* req,
             ::bbs::RepliesResp* resp) {
               return service->ListReplies(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::CreateReplyReq, ::bbs::CreateReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::CreateReplyReq* req,
             ::bbs::CreateReplyResp* resp) {
               return service->CreateReply(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::DeleteReplyReq, ::bbs::DeleteReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::DeleteReplyReq* req,
             ::bbs::DeleteReplyResp* resp) {
               return service->DeleteReply(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::LikeReplyReq, ::bbs::LikeReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::LikeReplyReq* req,
             ::bbs::LikeReplyResp* resp) {
               return service->LikeReply(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::LikeReplyReq, ::bbs::LikeReplyResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::LikeReplyReq* req,
             ::bbs::LikeReplyResp* resp) {
               return service->UnlikeReply(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[21],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::SearchReq, ::bbs::SearchResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::SearchReq* req,
             ::bbs::SearchResp* resp) {
               return service->Search(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[22],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::MyListReq, ::bbs::MyPostsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::MyListReq* req,
             ::bbs::MyPostsResp* resp) {
               return service->MyPosts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[23],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::MyListReq, ::bbs::MyRepliesResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::MyListReq* req,
             ::bbs::MyRepliesResp* resp) {
               return service->MyReplies(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[24],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::MyListReq, ::bbs::MyCollectionsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::MyListReq* req,
             ::bbs::MyCollectionsResp* resp) {
               return service->MyCollections(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[25],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::MyListReq, ::bbs::MyUsersResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::MyListReq* req,
             ::bbs::MyUsersResp* resp) {
               return service->MyFollowers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BbsService_method_names[26],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BbsService::Service, ::bbs::MyListReq, ::bbs::MyUsersResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BbsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bbs::MyListReq* req,
             ::bbs::MyUsersResp* resp) {
               return service->MyFollowing(ctx, req, resp);
             }, this)));
}

BbsService::Service::~Service() {
}

::grpc::Status BbsService::Service::GetForums(::grpc::ServerContext* context, const ::bbs::ForumsReq* request, ::bbs::ForumsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::GetForumDetail(::grpc::ServerContext* context, const ::bbs::ForumDetailReq* request, ::bbs::ForumDetailResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::FollowForum(::grpc::ServerContext* context, const ::bbs::FollowForumReq* request, ::bbs::FollowForumResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::UnfollowForum(::grpc::ServerContext* context, const ::bbs::FollowForumReq* request, ::bbs::FollowForumResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::GetFollowedForums(::grpc::ServerContext* context, const ::bbs::FollowedForumsReq* request, ::bbs::FollowedForumsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::ListPosts(::grpc::ServerContext* context, const ::bbs::PostsReq* request, ::bbs::PostsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::GetPostDetail(::grpc::ServerContext* context, const ::bbs::PostDetailReq* request, ::bbs::PostDetailResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::CreatePost(::grpc::ServerContext* context, const ::bbs::CreatePostReq* request, ::bbs::CreatePostResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::UpdatePost(::grpc::ServerContext* context, const ::bbs::UpdatePostReq* request, ::bbs::UpdatePostResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::DeletePost(::grpc::ServerContext* context, const ::bbs::DeletePostReq* request, ::bbs::DeletePostResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::LikePost(::grpc::ServerContext* context, const ::bbs::LikePostReq* request, ::bbs::LikePostResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::UnlikePost(::grpc::ServerContext* context, const ::bbs::LikePostReq* request, ::bbs::LikePostResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::CollectPost(::grpc::ServerContext* context, const ::bbs::CollectPostReq* request, ::bbs::CollectPostResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::UncollectPost(::grpc::ServerContext* context, const ::bbs::CollectPostReq* request, ::bbs::CollectPostResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::SetTopPost(::grpc::ServerContext* context, const ::bbs::SetTopReq* request, ::bbs::SetTopResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::SetEssencePost(::grpc::ServerContext* context, const ::bbs::SetEssenceReq* request, ::bbs::SetEssenceResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::ListReplies(::grpc::ServerContext* context, const ::bbs::RepliesReq* request, ::bbs::RepliesResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::CreateReply(::grpc::ServerContext* context, const ::bbs::CreateReplyReq* request, ::bbs::CreateReplyResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::DeleteReply(::grpc::ServerContext* context, const ::bbs::DeleteReplyReq* request, ::bbs::DeleteReplyResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::LikeReply(::grpc::ServerContext* context, const ::bbs::LikeReplyReq* request, ::bbs::LikeReplyResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::UnlikeReply(::grpc::ServerContext* context, const ::bbs::LikeReplyReq* request, ::bbs::LikeReplyResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::Search(::grpc::ServerContext* context, const ::bbs::SearchReq* request, ::bbs::SearchResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::MyPosts(::grpc::ServerContext* context, const ::bbs::MyListReq* request, ::bbs::MyPostsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::MyReplies(::grpc::ServerContext* context, const ::bbs::MyListReq* request, ::bbs::MyRepliesResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::MyCollections(::grpc::ServerContext* context, const ::bbs::MyListReq* request, ::bbs::MyCollectionsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::MyFollowers(::grpc::ServerContext* context, const ::bbs::MyListReq* request, ::bbs::MyUsersResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BbsService::Service::MyFollowing(::grpc::ServerContext* context, const ::bbs::MyListReq* request, ::bbs::MyUsersResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace bbs
#include <grpcpp/ports_undef.inc>

